# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: laravel-app
#     ports:
#       - 8000:80
#     volumes:
#       - .:/var/www/html
#     networks:
#       - laravel-network
#     depends_on:
#       - mysql
  
#   mysql:
#     image: mysql:8.0
#     container_name: mysql-container
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: laravel
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     ports:
#       - 3306:3306
#     networks:
#       - laravel-network

# networks:
#   laravel-network:
#     driver: bridge


services:
  app:
    container_name: pejem-backend
    image: pjedomex/oficial-pejem-php:82-2
    restart: always
    environment:
      APACHE_RUN_USER: '#1000'
      APACHE_RUN_GROUP: '#1000'
    build:
      context: .
    ports:
      - 80:80
    networks:
      - laravel-network
    volumes:
      - ./:/var/www
    depends_on:
      - db
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv6.conf.all.disable_ipv6: 1
      net.ipv4.tcp_fin_timeout: 10
      net.ipv4.tcp_keepalive_time: 10
  db:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
